version: '3'
services:
  app:
    container_name: docker-node-mongo-blog
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo-micro-blog
    image: mongo
    ports:
      - '27017:27017'
